// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqJEnxsWTDnm2MjhVBi1XM6uBqJuyYrfc',
    appId: '1:1089464265537:web:9e7fc5e37511cfb47d0fc0',
    messagingSenderId: '1089464265537',
    projectId: 'agent-app-398ce',
    authDomain: 'agent-app-398ce.firebaseapp.com',
    storageBucket: 'agent-app-398ce.appspot.com',
    measurementId: 'G-B4W5SJ4R46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7MK4dAPJG3MFcKwlJyZ_qgQHfvemy8g0',
    appId: '1:1089464265537:android:98060e3178f3a4bc7d0fc0',
    messagingSenderId: '1089464265537',
    projectId: 'agent-app-398ce',
    storageBucket: 'agent-app-398ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaeH6zQ-Qx9Q_d7DFQcOyoiH7T_hD1fGc',
    appId: '1:1089464265537:ios:75f67b7c5712661e7d0fc0',
    messagingSenderId: '1089464265537',
    projectId: 'agent-app-398ce',
    storageBucket: 'agent-app-398ce.appspot.com',
    androidClientId: '1089464265537-00bfrce45s7iktpovhr8c3jlfiiomff4.apps.googleusercontent.com',
    iosClientId: '1089464265537-a6oba0f79po1rmlth0tfbvo6kd57oj6m.apps.googleusercontent.com',
    iosBundleId: 'com.cattleguru.agent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaeH6zQ-Qx9Q_d7DFQcOyoiH7T_hD1fGc',
    appId: '1:1089464265537:ios:18996c1679df0e007d0fc0',
    messagingSenderId: '1089464265537',
    projectId: 'agent-app-398ce',
    storageBucket: 'agent-app-398ce.appspot.com',
    androidClientId: '1089464265537-00bfrce45s7iktpovhr8c3jlfiiomff4.apps.googleusercontent.com',
    iosClientId: '1089464265537-cn9lbglnoj5n1ahfbvbl59tmovrr2g9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleGuruAgentApp',
  );
}
